- name: Install Numix GTK
  apt:
    name: numix-gtk-theme
    state: present

- name: Install prerequisites for i3status-rust
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libdbus-1-dev
    - fonts-font-awesome
    - fonts-powerline

- name: Install i3status-rust
  shell: |
    mkdir -p ~/Development
    cd ~/Development
    git clone https://github.com/greshake/i3status-rust
    cd i3status-rust
    cargo install --path .
    ./install.sh
  become: False

# - name: Install gruvbox shell theme
#   shell: bash -c "$(wget -qO- https://raw.githubusercontent.com/Mayccoll/Gogh/master/themes/aci.sh)"
#   become: False

- name: Install betterlockscreen
  shell: bash -c "$(wget -qO- https://gist.githubusercontent.com/neetjn/6dbde42fa929ea114ad37c401e47fc22/raw/241ef0da5e788cad8f9d824ebd47005f905500d1/betterlockscreen-auto.sh)"

- name: Cache betterlockscreen default image
  shell: "betterlockscreen -u {{home_directory}}/.local/share/backgrounds/0023.png"

